//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultitoolWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultitoolWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary data (.dat stands for .data) files. Often used by application for diverse purposes, some are critical for them to work..
        /// </summary>
        internal static string _dat {
            get {
                return ResourceManager.GetString(".dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file, generated by applications (and system) to save data. Usually contains messages about events that occurred during the app execution, such as errors. Used for telemetry..
        /// </summary>
        internal static string _log {
            get {
                return ResourceManager.GetString(".log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System files..
        /// </summary>
        internal static string _sys {
            get {
                return ResourceManager.GetString(".sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is related to autochk.exe, which is sometimes run by Windows at startup to check for filesystem issues. Used for telemetry..
        /// </summary>
        internal static string bootTel_dat {
            get {
                return ResourceManager.GetString("bootTel.dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File used by windows to save the state of the computer (by saving the RAM contents to a file) when it shuts down/hibernate..
        /// </summary>
        internal static string hiberfile_sys {
            get {
                return ResourceManager.GetString("hiberfile.sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Packages\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\LocalState\Assets.
        /// </summary>
        internal static string SpotlightWallpapers {
            get {
                return ResourceManager.GetString("SpotlightWallpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File used by the system when the volatile memory (RAM) is full. It allows to expand the computer&apos;s memory. If the file is big, it usually means that the system is often overloaded (memory wise) and that the system needs more volatile memory to work..
        /// </summary>
        internal static string swapfile_sys {
            get {
                return ResourceManager.GetString("swapfile.sys", resourceCulture);
            }
        }
    }
}
